### ISSUE TITLE
Can't detect `gulpFile.js`

### ISSUE THREAD

**Issue by hanifbbz** [jacogr/atom-gulp-control#13]
Thanks for the awesome plugin.

In our project for some reasons the gulpfile.js has a big F. And this plugin can't find it showing the following error:

```Unable to find [G|g]ulpfile.[js|cofee]```

It would be great if it was case insensitive. Gulp itself seems to be case insensitive (at least on Windows).

**Comment by jacogr** [comment]
Fixed in https://github.com/jacogr/atom-gulp-control/commit/c9bbc3c97bbecb446f5ff4cb83a3886b79aea7be , 0.4.1 released that addresses
