### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by akhyarrh** [jacogr/atom-gulp-control#19]
![2015-06-30_02-42-12](https://cloud.githubusercontent.com/assets/10618799/8415509/c47bee36-1ed1-11e5-8398-ac25ec5e5799.png)

I think this is caused by my node path because node location is on `/home/akhyar/.nvm/versions/node/v0.12.5/bin/node`, installed using nvm. I hope there's something we can do to solve this.

Thanks

**Comment by janbaykara** [comment]
Ditto, using .nvm on Mac. Error was: 
> `env: node: No such file or directory`

**Comment by lxeran** [comment]
same here, using .nvm.

**Comment by sectsect** [comment]
I was able to solve this problem. (using nodebrew)
Line: 121   .atom/packages/gulp-control/lib/gulp-control-view.coffee
-  else "#{process.env.PATH}:/usr/local/bin"
+ else "#{process.env.PATH}:/Users/{username}/.nodebrew/current/bin"

**Comment by akhyarrh** [comment]
Dirty but works. Anyway, on `nvm`:
`else "#{process.env.PATH}:/home/{user}/.nvm/versions/node/{node version}/bin"`
The bad part is to update that path after every update...
and if you're lazy like me, go take a selfie

**Comment by sectsect** [comment]
Exactly. My way is the last resort.

**Comment by acburdine** [comment]
The main issue with this is because the system $PATH variable is not imported unless you run atom from the command line. I created a PR that adds a config option to specify the node path

**Comment by BabylonSix** [comment]
on nvm - not working for me. why not add a path option that the user can set like in eslint?

**Comment by AlexGustafsson** [comment]
Bump for the ability to decide where node is located.
