### ISSUE TITLE
gulpfile.babel.js

### ISSUE THREAD

**Issue by richlewis42** [jacogr/atom-gulp-control#25]
Support for gulpfile.babel.js would be appreciated!

**Comment by OEvgeny** [comment]
:+1:

**Comment by sergiu-paraschiv** [comment]
https://github.com/jacogr/atom-gulp-control/pull/23

**Comment by richlewis42** [comment]
Huh didn't see this originally - it is still not detecting my gulpfile.babel.js however...

**Comment by OEvgeny** [comment]
It's not relesed yet...

**Comment by jacogr** [comment]
patch released
